import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import test from "node:test";
import {adjustCustomerLoyalty,fetchCustomerLoyalty,saveLoyaltyProgram} from "../../src/services/loyaltyApi.js";
import {isLoyaltyDraftDirty,loyaltyDraftSignature} from "../../src/admin/loyaltyDraft.js";

const response=(status,payload={})=>({ok:status>=200&&status<300,status,json:async()=>payload});

test("customer loyalty derives identity from authenticated cookie",async()=>{let request;await fetchCustomerLoyalty({apiBaseUrl:"https://api.example",fetchImpl:async(...args)=>{request=args;return response(200,{programs:[]})}});assert.equal(request[0],"https://api.example/api/v1/customer/loyalty");assert.equal(request[1].credentials,"include");assert.equal(request[1].method,"GET")});

test("Owner program and adjustment mutations carry CSRF and explicit audit reason",async()=>{const requests=[];const fetchImpl=async(...args)=>{requests.push(args);return response(args[1].method==="POST"?201:200,{})};await saveLoyaltyProgram({name:"Coffee & Tea Loyalty"},"csrf",{fetchImpl});await adjustCustomerLoyalty({customer_user_id:"customer",program_id:"program",quantity:-1,reason:"Correction"},"csrf",{fetchImpl});assert.equal(requests[0][1].headers["X-CSRF-Token"],"csrf");assert.deepEqual(JSON.parse(requests[1][1].body),{customer_user_id:"customer",program_id:"program",quantity:-1,reason:"Correction"})});

test("Home and Account render authenticated real state, errors, and signed-out invitation",()=>{const home=readFileSync(new URL("../../src/pages/HomePage.jsx",import.meta.url),"utf8");const card=readFileSync(new URL("../../src/components/LoyaltyCard.jsx",import.meta.url),"utf8");const account=readFileSync(new URL("../../src/pages/AccountPage.jsx",import.meta.url),"utf8");assert.match(home,/fetchCustomerLoyalty/);assert.match(card,/Sign in to collect loyalty stamps/);assert.match(card,/Free drink ready/);assert.match(card,/Your saved progress is not affected/);assert.match(account,/AccountLoyalty/)});

test("Owner Loyalty includes searchable real products, status, and audited adjustment",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");assert.match(page,/Search loyalty products/);assert.match(page,/Earns a stamp/);assert.match(page,/Can be a free reward/);assert.match(page,/Program status/);assert.match(page,/Required reason/);assert.match(page,/Save changes/)});

test("Owner Loyalty product controls are associated, touch-oriented, and responsive",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");const styles=readFileSync(new URL("../../src/style.css",import.meta.url),"utf8");assert.match(page,/htmlFor={earningId}/);assert.match(page,/id={earningId}/);assert.match(page,/htmlFor={rewardId}/);assert.match(page,/id={rewardId}/);assert.match(page,/loyalty-eligibility-controls/);assert.match(styles,/\.loyalty-program-form \.loyalty-eligibility-control[^}]*align-items: center;[^}]*box-sizing: border-box;[^}]*min-height: 48px/);assert.match(styles,/:has\(input:checked\)/);assert.match(styles,/@media \(max-width: 480px\)[^{]*{[^}]*\.loyalty-eligibility-controls/s)});

test("Owner Loyalty filtering preserves the unsaved eligibility draft",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");assert.match(page,/const filtered=useMemo\(\(\)=>\(data\?\.products\|\|\[\]\)\.filter/);assert.match(page,/function toggle\(id,field\)\{editForm/);assert.match(page,/checked={form\.earning_product_ids\.includes\(product\.id\)}/);assert.match(page,/checked={form\.reward_product_ids\.includes\(product\.id\)}/)});

test("Owner Loyalty filtered product list expands with the page without internal overflow",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");const styles=readFileSync(new URL("../../src/style.css",import.meta.url),"utf8");assert.match(page,/className="loyalty-product-list">{filtered\.map/);assert.match(styles,/\.loyalty-product-list \{[^}]*max-height: none;[^}]*overflow: visible;[^}]*width: 100%;/);assert.doesNotMatch(styles,/\.loyalty-product-list \{[^}]*(?:overflow: auto|max-height: 520px)/);assert.match(styles,/\.loyalty-product-list article \{[^}]*min-width: 0/);assert.match(styles,/\.loyalty-eligibility-controls \{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)[^}]*min-width: 0/)});

test("Owner Loyalty filters are a matched accessible pair that stack on narrow screens",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");const styles=readFileSync(new URL("../../src/style.css",import.meta.url),"utf8");assert.match(page,/className="product-search loyalty-search-control"><Search aria-hidden="true" size=\{18\}\/><input aria-label="Search loyalty products"/);assert.match(page,/className="loyalty-category-filter"/);assert.match(page,/aria-label="Filter loyalty products by category"/);assert.match(styles,/\.loyalty-product-filters \{[^}]*align-items: stretch;[^}]*gap: 12px;[^}]*grid-template-columns: minmax\(0, 1fr\) minmax\(220px, \.4fr\)/);assert.match(styles,/\.loyalty-program-form \.loyalty-product-filters label \{[^}]*align-items: center;[^}]*display: flex;[^}]*height: 50px;[^}]*padding: 0 14px/);assert.match(styles,/\.loyalty-search-control svg \{[^}]*flex: 0 0 auto/);assert.match(styles,/\.loyalty-program-form \.loyalty-product-filters input, \.loyalty-program-form \.loyalty-product-filters select \{[^}]*height: 48px;[^}]*min-height: 48px;[^}]*padding: 0/);assert.match(styles,/@media \(max-width: 680px\)[^{]*{[\s\S]*?\.loyalty-product-filters \{ grid-template-columns: 1fr; \}/)});

test("Owner Loyalty UI refinement leaves eligibility arrays and save submission intact",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");assert.match(page,/earning_product_ids:p\.earning_product_ids\|\|\[\]/);assert.match(page,/reward_product_ids:p\.reward_product_ids\|\|\[\]/);assert.match(page,/saveLoyaltyProgram\(form,session\.csrf_token\)/);assert.match(page,/function toggle\(id,field\)\{editForm\(v=>\(\{\.\.\.v,\[field\]:v\[field\]\.includes\(id\)\?v\[field\]\.filter\(x=>x!==id\):\[\.\.\.v\[field\],id\]\}\)\)\}/)});

test("Owner Loyalty uses a wide bounded desktop workspace without changing global Operations width",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");const styles=readFileSync(new URL("../../src/style.css",import.meta.url),"utf8");assert.match(page,/className="page-section loyalty-admin-page"/);assert.match(styles,/\.loyalty-admin-page \{[^}]*width: min\(100%, 1080px\)/);assert.match(styles,/\.loyalty-admin-page \.operations-panel \{[^}]*max-width: none;[^}]*width: 100%/);assert.doesNotMatch(styles,/\.operations-panel \{[^}]*width: min\(1080px/)});

test("Owner Loyalty program and product rows use responsive desktop grids",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");const styles=readFileSync(new URL("../../src/style.css",import.meta.url),"utf8");assert.match(page,/className="operations-panel loyalty-program-settings"/);assert.match(page,/className="form-grid loyalty-program-basics"/);assert.match(page,/className="form-grid loyalty-program-reward"/);assert.match(styles,/\.loyalty-program-basics, \.loyalty-program-reward \{[^}]*grid-template-columns: minmax\(0, 1fr\) minmax\(280px, \.55fr\);[^}]*gap: 16px/);assert.match(styles,/\.loyalty-program-settings input, \.loyalty-program-settings select \{[^}]*min-height: 46px/);assert.match(styles,/\.loyalty-product-list article \{[^}]*grid-template-columns: minmax\(250px, 1fr\) minmax\(430px, 1\.05fr\)[^}]*padding: 10px 14px/);assert.match(styles,/\.loyalty-eligibility-controls \{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);assert.match(styles,/@media \(max-width: 820px\)[^{]*\{[\s\S]*?\.loyalty-program-basics, \.loyalty-program-reward \{ grid-template-columns: 1fr; \}[\s\S]*?\.loyalty-product-list article \{ align-items: start; grid-template-columns: 1fr; \}/)});

test("Owner Loyalty paired reward controls align without changing field semantics",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");const styles=readFileSync(new URL("../../src/style.css",import.meta.url),"utf8");assert.match(page,/<div className="form-grid loyalty-program-reward"><label><span>Stamps required before reward<\/span><input[^>]*type="number"[\s\S]*?<small>6 means “Buy 6, get your 7th free\.”<\/small><\/label><label><span>Reward description<\/span><input required maxLength="200" value=\{form\.reward_description\} onChange=\{e=>editForm/);assert.match(page,/<span>Customer-facing description<\/span><textarea/);assert.match(styles,/\.loyalty-program-reward \{ align-items: start; \}/);assert.match(styles,/\.loyalty-program-settings input, \.loyalty-program-settings select \{ min-height: 46px; \}/);assert.match(page,/saveLoyaltyProgram\(form,session\.csrf_token\)/);assert.equal((page.match(/<SaveActions\b/g)||[]).length,2)});

test("Owner Loyalty desktop layout preserves overflow safety, matched filters, and mobile controls",()=>{const styles=readFileSync(new URL("../../src/style.css",import.meta.url),"utf8");assert.match(styles,/\.loyalty-product-list \{[^}]*max-height: none;[^}]*overflow: visible;[^}]*width: 100%/);assert.match(styles,/\.loyalty-product-filters \{[^}]*grid-template-columns: minmax\(0, 1fr\) minmax\(220px, \.4fr\)/);assert.match(styles,/\.loyalty-program-form \.loyalty-product-filters input, \.loyalty-program-form \.loyalty-product-filters select \{[^}]*min-height: 48px/);assert.match(styles,/@media \(max-width: 680px\)[^{]*\{[\s\S]*?\.loyalty-product-filters \{ grid-template-columns: 1fr; \}/);assert.match(styles,/@media \(max-width: 480px\)[^{]*\{[^}]*\.loyalty-eligibility-controls \{ grid-template-columns: 1fr; \}/);assert.doesNotMatch(styles,/\.loyalty-product-list \{[^}]*(?:overflow-x|overflow-y|overflow: auto)/)});

test("Owner Loyalty has exactly two coordinated complete-program Save actions in card headers",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");const styles=readFileSync(new URL("../../src/style.css",import.meta.url),"utf8");const renderedSaveActions=page.match(/<SaveActions\b/g)||[];assert.equal(renderedSaveActions.length,2);assert.match(page,/loyalty-program-settings"><div className="loyalty-section-heading"><h2>Loyalty program<\/h2><SaveActions/);assert.match(page,/loyalty-products"><div className="loyalty-section-heading loyalty-products-heading">[\s\S]*?<SaveActions[\s\S]*?<div className="product-quick-tools loyalty-product-filters"/);assert.doesNotMatch(page,/<\/section><button className="primary-button loyalty-save-button"/);assert.match(page,/function SaveActions[\s\S]*?disabled=\{saving\} type="submit">\{saving\?"Saving…":"Save changes"\}/);assert.match(page,/<form className="loyalty-program-form" onSubmit=\{save\}>[\s\S]*?loyalty-program-settings[\s\S]*?loyalty-products[\s\S]*?loyalty-product-list[\s\S]*?<\/section><\/form>/);assert.match(page,/saveLoyaltyProgram\(form,session\.csrf_token\)/);assert.match(styles,/\.loyalty-section-heading \{[^}]*align-items: flex-start;[^}]*display: flex;[^}]*justify-content: space-between/);assert.match(styles,/\.loyalty-save-actions \{[^}]*align-items: center;[^}]*display: flex/);assert.match(styles,/@media \(max-width: 680px\)[^{]*\{[\s\S]*?\.loyalty-section-heading \{ align-items: stretch; flex-direction: column; \}[\s\S]*?\.loyalty-save-button \{ width: 100%; \}/);assert.match(styles,/\.loyalty-admin-page \.loyalty-adjustment \{[^}]*max-width: none;[^}]*width: 100%/)});

const savedDraft={id:"program",name:"Coffee & Tea Loyalty",enabled:false,description:"Buy drinks",stamps_required:6,reward_description:"Free drink",earning_product_ids:["tea","coffee"],reward_product_ids:["coffee"]};

test("Owner Loyalty dirty comparison covers every persisted field and clean reverts",()=>{assert.equal(isLoyaltyDraftDirty(savedDraft,{...savedDraft}),false);for(const change of [{name:"Other"},{enabled:true},{description:"Changed"},{stamps_required:7},{reward_description:"Changed"},{earning_product_ids:["tea"]},{reward_product_ids:["coffee","tea"]}]){const changed={...savedDraft,...change};assert.equal(isLoyaltyDraftDirty(changed,savedDraft),true);assert.equal(isLoyaltyDraftDirty({...changed,...savedDraft},savedDraft),false)}});

test("Owner Loyalty product eligibility comparison is order-insensitive set comparison",()=>{const reordered={...savedDraft,earning_product_ids:["coffee","tea"],reward_product_ids:["coffee","coffee"]};assert.equal(loyaltyDraftSignature(reordered),loyaltyDraftSignature(savedDraft));assert.equal(isLoyaltyDraftDirty(reordered,savedDraft),false)});

test("Owner Loyalty transient search, filter, and adjustment values are excluded from dirty state",()=>{const withTransient={...savedDraft,query:"latte",category:"Tea",customerQuery:"Jessie",adjustment:{quantity:3,reason:"Transfer"},loading:true,error:"temporary"};assert.equal(isLoyaltyDraftDirty(withTransient,savedDraft),false)});

test("Owner Loyalty success and failure preserve the authoritative dirty baseline correctly",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");assert.match(page,/setSavedForm\(draft\)/);assert.match(page,/const authoritativeDraft=draftFrom\(next\);setData\(next\);setForm\(authoritativeDraft\);setSavedForm\(authoritativeDraft\);setSaveConfirmed\(true\)/);assert.match(page,/catch\(e\)\{setNotice\(e\.message\)\}finally/);assert.doesNotMatch(page,/catch\(e\)\{[^}]*setSavedForm/);assert.match(page,/savingRef\.current=true/);assert.match(page,/if\(savingRef\.current\)return/)});

test("Owner Loyalty guards dirty internal and browser navigation with an accessible safe-default dialog",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");assert.match(page,/window\.addEventListener\("beforeunload",beforeUnload\)/);assert.match(page,/return\(\)=>window\.removeEventListener\("beforeunload",beforeUnload\)/);assert.match(page,/window\.navigation/);assert.match(page,/navigationApi\.traverseTo\(key\)/);assert.match(page,/document\.addEventListener\("click",onClick,true\)/);assert.match(page,/<dialog aria-describedby="unsaved-loyalty-message" aria-labelledby="unsaved-loyalty-title"/);assert.match(page,/<h2 id="unsaved-loyalty-title">Unsaved loyalty changes<\/h2>/);assert.match(page,/<button autoFocus className="secondary-button"[^>]*>Keep editing<\/button>/);assert.match(page,/>Leave without saving<\/button>/);assert.match(page,/onCancel=\{keepEditing\}/)});

test("Owner Loyalty dirty and saved feedback is shared, textual, stable, and responsive",()=>{const page=readFileSync(new URL("../../src/admin/LoyaltyPage.jsx",import.meta.url),"utf8");const styles=readFileSync(new URL("../../src/style.css",import.meta.url),"utf8");assert.match(page,/dirty\?"Unsaved changes":saved\?"Changes saved":""/);assert.match(page,/aria-live=\{announce\?"polite":undefined\}/);assert.match(styles,/\.loyalty-save-status \{[^}]*min-height: 1\.3em;[^}]*min-width: 112px/);assert.match(styles,/\.loyalty-save-status\.is-unsaved/);assert.match(styles,/\.loyalty-save-status\.is-saved/);assert.match(styles,/@media \(max-width: 680px\)[^{]*\{[\s\S]*?\.loyalty-save-actions \{ align-items: stretch; display: grid;[^}]*\}[\s\S]*?\.loyalty-save-status \{ min-width: 0; text-align: left; \}/)});
