import { Link } from "react-router-dom";

export default function LoyaltyCard({program, signedIn, compact=false, loading=false, error=""}) {
  if(!signedIn) return <section className={`content-block app-content-block loyalty-card real-loyalty${compact?" compact":""}`} aria-labelledby="loyalty-heading"><div><p className="eyebrow">Stamp card</p><h2 id="loyalty-heading">Coffee & Tea Loyalty</h2><p>Sign in to collect loyalty stamps.</p><Link to="/account/sign-in">Sign in</Link></div></section>;
  if(loading) return <section className={`content-block app-content-block loyalty-card real-loyalty${compact?" compact":""}`} aria-labelledby="loyalty-heading"><div><p className="eyebrow">Stamp card</p><h2 id="loyalty-heading">Loyalty</h2><p>Loading your stamp card…</p></div></section>;
  if(error) return <section className={`content-block app-content-block loyalty-card real-loyalty${compact?" compact":""}`} aria-labelledby="loyalty-heading"><div><p className="eyebrow">Stamp card</p><h2 id="loyalty-heading">Loyalty unavailable</h2><p>We couldn’t load your stamp card. Your saved progress is not affected.</p></div></section>;
  if(!program) return <section className={`content-block app-content-block loyalty-card real-loyalty${compact?" compact":""}`} aria-labelledby="loyalty-heading"><div><p className="eyebrow">Stamp card</p><h2 id="loyalty-heading">Loyalty</h2><p>The café loyalty card is not active yet.</p></div></section>;
  const rewardReady=program.rewards_available>0;
  return <section className={`content-block app-content-block loyalty-card real-loyalty${compact?" compact":""}`} aria-labelledby="loyalty-heading"><div><p className="eyebrow">Stamp card</p><h2 id="loyalty-heading">{program.name}</h2><p>{!program.enabled?"This card is currently paused. Your progress is saved.":rewardReady?"Free drink ready":`${program.remaining} more until your free drink`}</p></div><div><strong className="loyalty-progress-copy">{program.stamps} of {program.stamps_required} stamps</strong><div className="stamp-row" aria-label={`${program.stamps} of ${program.stamps_required} stamps collected`}>{Array.from({length:program.stamps_required}).map((_,index)=>{const earned=index<program.stamps;return <span aria-label={`Stamp ${index+1}: ${earned?"earned":"not earned"}`} className={earned?"filled":"unearned"} key={index} role="img"/>})}</div>{rewardReady?<strong className="loyalty-reward-ready">{program.rewards_available} free {program.rewards_available===1?"drink":"drinks"} ready</strong>:null}</div></section>;
}
