import { useEffect, useMemo, useState } from "react";
import { fetchDesignDraft, fetchDesignVersions, fetchMedia, publishDesign, revertDesign, saveDesignDraft, uploadMedia } from "../services/designStudioApi.js";
import { useOwnerAuth } from "../auth/OwnerAuthContext.jsx";
import { useCatalogProducts } from "../stores/catalogStore.js";
import { Link } from "react-router-dom";

const templates = [
  { id: "modern", name: "Modern", note: "Bold hero, horizontal categories, crisp product grid" },
  { id: "minimal", name: "Minimal", note: "Compact navigation, editorial spacing, quiet cards" },
  { id: "cozy", name: "Cozy", note: "Warm hero, welcoming sections, comfortable cards" },
];
const allSections = ["hero", "announcement", "categories", "quickOrder"];
function channel(value) { const normalized=value/255;return normalized<=.04045?normalized/12.92:((normalized+.055)/1.055)**2.4; }
function luminance(color) { return .2126*channel(parseInt(color.slice(1,3),16))+.7152*channel(parseInt(color.slice(3,5),16))+.0722*channel(parseInt(color.slice(5,7),16)); }
function contrast(a,b) { const values=[luminance(a),luminance(b)].sort((left,right)=>right-left);return (values[0]+.05)/(values[1]+.05); }
export default function DesignStudioPage() {
  const { session } = useOwnerAuth(); const { products } = useCatalogProducts();
  const [draft, setDraft] = useState(null); const [status, setStatus] = useState("loading"); const [message, setMessage] = useState("");
  const [versions, setVersions] = useState([]);
  const [media,setMedia]=useState([]); const [uploading,setUploading]=useState(false);
  const refreshVersions = () => fetchDesignVersions().then(setVersions);
  useEffect(() => { Promise.all([fetchDesignDraft(), fetchDesignVersions(),fetchMedia()]).then(([value, history,assets]) => { setDraft(value); setVersions(history);setMedia(assets); setStatus("ready"); }).catch((error) => { setMessage(error.message); setStatus("error"); }); }, []);
  const sample = useMemo(() => products.filter((p) => p.published).slice(0, 4), [products]);
  if (status === "loading") return <section className="page-section"><h1>Design Studio</h1><p>Loading your draft…</p></section>;
  if (!draft) return <section className="page-section"><h1>Design Studio</h1><p className="owner-page-message error">{message}</p></section>;
  const config = draft.config;
  const update = (patch) => setDraft((value) => ({ ...value, config: { ...value.config, ...patch } }));
  async function save() { try { setStatus("saving"); const value=await saveDesignDraft({ revision:draft.revision, config },session.csrf_token); setDraft(value); setMessage("Draft saved. Your public storefront is unchanged."); setStatus("ready"); } catch(error){setMessage(error.message);setStatus("error");} }
  async function publish(){ try{setStatus("publishing");const value=await publishDesign(session.csrf_token);await refreshVersions();setMessage(`Version ${value.version} is now live.`);setStatus("ready");}catch(error){setMessage(error.message);setStatus("error");} }
  async function revert(item){ if (!globalThis.confirm?.(`Restore version ${item.version}? Your menu and orders will not change.`)) return; try{setStatus("publishing");const value=await revertDesign(item.id,session.csrf_token);const [nextDraft]=await Promise.all([fetchDesignDraft(),refreshVersions()]);setDraft(nextDraft);setMessage(`Version ${value.version} is live, restored from version ${item.version}.`);setStatus("ready");}catch(error){setMessage(error.message);setStatus("error");} }
  async function upload(event){const file=event.target.files?.[0];if(!file)return;try{setUploading(true);const asset=await uploadMedia(file,`${config.displayName} brand image`,session.csrf_token);setMedia((items)=>[asset,...items]);setMessage("Image uploaded to your private media library.");}catch(error){setMessage(error.message);}finally{setUploading(false);event.target.value="";}}
  const moveSection=(index,direction)=>{const sections=[...config.sections];const target=index+direction;if(target<0||target>=sections.length)return;[sections[index],sections[target]]=[sections[target],sections[index]];update({sections});};
  const toggleSection=(section,enabled)=>update({sections:enabled?[...config.sections,section]:config.sections.filter((item)=>item!==section)});
  const mediaUrl=(id)=>media.find((asset)=>asset.id===id)?.ownerUrl||null;
  const contrastValid=contrast(config.colors.text,config.colors.background)>=4.5&&contrast(config.colors.text,config.colors.surface)>=4.5;
  return <section className="design-studio">
    <header className="design-studio-header"><div><p className="eyebrow">Your storefront</p><h1>Design Studio</h1><p>Customize a guided template. Menu, prices, and availability always stay live.</p></div><div className="design-actions"><Link className="secondary-button" to="/admin/design/preview">Full preview</Link><button className="secondary-button" disabled={status!=="ready"} onClick={save}>Save draft</button><button className="primary-button" disabled={status!=="ready"} onClick={publish}>Publish</button></div></header>
    {message ? <p className="owner-page-message" aria-live="polite">{message}</p> : null}
    <div className="studio-workspace"><aside className="studio-controls" aria-label="Design controls">
      <fieldset><legend>Template</legend>{templates.map((item)=><label className="template-choice" key={item.id}><input type="radio" name="template" checked={config.template===item.id} onChange={()=>update({template:item.id})}/><span><strong>{item.name}</strong><small>{item.note}</small></span></label>)}</fieldset>
      <label>Business name<input value={config.displayName} maxLength="80" onChange={(e)=>update({displayName:e.target.value})}/></label>
      <label>Tagline<input value={config.tagline} maxLength="140" onChange={(e)=>update({tagline:e.target.value})}/></label>
      <div className="color-controls">{Object.entries(config.colors).map(([key,value])=><label key={key}>{key}<input type="color" value={value} onChange={(e)=>update({colors:{...config.colors,[key]:e.target.value}})}/></label>)}</div>
      {!contrastValid?<p className="owner-page-message error" role="alert">Text needs at least 4.5:1 contrast against both the page background and card surface before this draft can be saved.</p>:null}
      <label>Typography<select value={config.typography} onChange={(e)=>update({typography:e.target.value})}><option value="modern">Modern</option><option value="classic">Classic</option><option value="friendly">Friendly</option></select></label>
      <label>Button style<select value={config.buttonStyle} onChange={(e)=>update({buttonStyle:e.target.value})}><option value="rounded">Rounded</option><option value="square">Square</option><option value="pill">Pill</option></select></label>
      <fieldset><legend>Brand images</legend><label>Upload image<input type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={upload}/></label><label>Logo<select value={config.logoMediaId||""} onChange={(e)=>update({logoMediaId:e.target.value||null})}><option value="">No logo</option>{media.map((asset)=><option key={asset.id} value={asset.id}>{asset.altText||asset.storageKey||"Uploaded image"}</option>)}</select></label><label>Hero image<select value={config.hero?.mediaId||""} onChange={(e)=>update({hero:{mode:e.target.value?"image":"color",mediaId:e.target.value||null}})}><option value="">Use brand color</option>{media.map((asset)=><option key={asset.id} value={asset.id}>{asset.altText||asset.storageKey||"Uploaded image"}</option>)}</select></label></fieldset>
      <fieldset><legend>Homepage sections</legend>{allSections.map((section)=>{const index=config.sections.indexOf(section);const enabled=index>=0;return <div className="section-order-row" key={section}><label className="checkbox-label"><input type="checkbox" checked={enabled} onChange={(event)=>toggleSection(section,event.target.checked)}/><span>{section}</span></label>{enabled?<><button type="button" className="secondary-button" aria-label={`Move ${section} up`} disabled={index===0} onClick={()=>moveSection(index,-1)}>↑</button><button type="button" className="secondary-button" aria-label={`Move ${section} down`} disabled={index===config.sections.length-1} onClick={()=>moveSection(index,1)}>↓</button></>:null}</div>})}</fieldset>
      <label>Category presentation<select value={config.categoryPresentation} onChange={(e)=>update({categoryPresentation:e.target.value})}><option value="cards">Cards</option><option value="list">List</option></select></label>
      <label>Product cards<select value={config.productCardPresentation} onChange={(e)=>update({productCardPresentation:e.target.value})}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label>
      <label className="checkbox-label"><input type="checkbox" checked={config.announcement?.enabled||false} onChange={(e)=>update({announcement:{...(config.announcement||{text:""}),enabled:e.target.checked}})}/>Show announcement</label>
      <label>Announcement<input value={config.announcement?.text||""} maxLength="180" onChange={(e)=>update({announcement:{...(config.announcement||{enabled:false}),text:e.target.value}})}/></label>
      <fieldset><legend>Installed app appearance</legend><label>Short name<input value={config.pwa.shortName} maxLength="30" onChange={(e)=>update({pwa:{...config.pwa,shortName:e.target.value}})}/></label><label>Theme color<input type="color" value={config.pwa.themeColor} onChange={(e)=>update({pwa:{...config.pwa,themeColor:e.target.value}})}/></label><label>Launch background<input type="color" value={config.pwa.backgroundColor} onChange={(e)=>update({pwa:{...config.pwa,backgroundColor:e.target.value}})}/></label></fieldset>
      <section className="design-history"><h2>Published versions</h2>{versions.length ? <ul>{versions.map((item)=><li key={item.id}><span>Version {item.version}{item.isCurrent ? " · Live" : ""}<small>{new Date(item.publishedAt).toLocaleString()}</small></span>{!item.isCurrent ? <button className="secondary-button" type="button" disabled={status!=="ready"} onClick={()=>revert(item)}>Restore</button> : null}</li>)}</ul> : <p>Nothing has been published yet.</p>}</section>
    </aside><div className="phone-preview-wrap"><p className="preview-badge">Draft preview · real catalog · checkout disabled</p><div className={`phone-preview template-${config.template}`} style={{"--preview-primary":config.colors.primary,"--preview-accent":config.colors.accent,"--preview-bg":config.colors.background,"--preview-surface":config.colors.surface,"--preview-text":config.colors.text}}><div className="phone-speaker"/><nav>{config.logoMediaId?<img className="preview-logo" src={mediaUrl(config.logoMediaId)} alt=""/>:config.displayName}<span>Bag</span></nav>{config.sections.includes("announcement")&&config.announcement?.enabled&&config.announcement.text?<p className="preview-announcement">{config.announcement.text}</p>:null}{config.sections.includes("hero")?<header style={config.hero?.mediaId?{backgroundImage:`linear-gradient(#0005,#0005),url(${mediaUrl(config.hero.mediaId)})`}:undefined}><p>{config.tagline}</p><h2>{config.displayName}</h2><button type="button" disabled>Preview only</button></header>:null}{config.sections.some((section)=>section==="categories"||section==="quickOrder")?<main><h3>Popular today</h3><div className={`preview-products presentation-${config.productCardPresentation}`}>{sample.length?sample.map((p)=><article key={p.id}><div/><strong>{p.name}</strong><span>${Number(p.price).toFixed(2)}</span></article>):<p>Your real products will appear here.</p>}</div></main>:null}</div></div></div>
  </section>;
}
