import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import LayoutPhonePreview from "../design/LayoutPhonePreview.jsx";
import { layoutChoices } from "../design/layoutDefinitions.js";
import { useOwnerAuth } from "../auth/OwnerAuthContext.jsx";
import { archiveMedia, fetchDesignDraft, fetchDesignVersions, fetchMedia, fetchReadiness, publishDesign, revertDesign, saveDesignDraft, uploadMedia } from "../services/designStudioApi.js";
import { useCatalogProducts } from "../stores/catalogStore.js";

const builderStages = [
  { label: "Choose your app layout", to: "/admin/design" }, { label: "Make it yours", to: "/admin/design#brand" },
  { label: "Business details", to: "/admin/setup#business" }, { label: "Build your menu", to: "/admin/products" },
  { label: "Set up ordering", to: "/admin/scheduling" }, { label: "Connect payments", to: "/admin/setup#payments" },
  { label: "Preview", to: "/admin/design/preview" }, { label: "Launch", to: "/admin/launch" },
];
function channel(value){const normalized=value/255;return normalized<=.04045?normalized/12.92:((normalized+.055)/1.055)**2.4;}
function luminance(color){return .2126*channel(parseInt(color.slice(1,3),16))+.7152*channel(parseInt(color.slice(3,5),16))+.0722*channel(parseInt(color.slice(5,7),16));}
function contrast(a,b){const values=[luminance(a),luminance(b)].sort((left,right)=>right-left);return(values[0]+.05)/(values[1]+.05);}

export default function DesignStudioPage({guided=false,onContinue,wizardStep=null}){
  const {session}=useOwnerAuth();const {categories,products}=useCatalogProducts();
  const [draft,setDraft]=useState(null);const [savedConfig,setSavedConfig]=useState(null);const [status,setStatus]=useState("loading");const [message,setMessage]=useState("");
  const [versions,setVersions]=useState([]);const [media,setMedia]=useState([]);const [uploading,setUploading]=useState(false);const [readiness,setReadiness]=useState(null);const [mobileView,setMobileView]=useState("edit");
  const refreshVersions=()=>fetchDesignVersions().then(setVersions);
  useEffect(()=>{Promise.all([fetchDesignDraft(),fetchDesignVersions(),fetchMedia(),fetchReadiness()]).then(([value,history,assets,checks])=>{setDraft(value);setSavedConfig(value.config);setVersions(history);setMedia(assets);setReadiness(checks);setStatus("ready");}).catch((error)=>{setMessage(error.message);setStatus("error");});},[]);
  if(status==="loading")return <section className="page-section"><h1>Design Studio</h1><p>Loading your design…</p></section>;
  if(!draft)return <section className="page-section"><h1>Design Studio</h1><p className="owner-page-message error">{message}</p></section>;
  const config=draft.config;const dirty=JSON.stringify(config)!==JSON.stringify(savedConfig);const contrastValid=contrast(config.colors.text,config.colors.background)>=4.5&&contrast(config.colors.text,config.colors.surface)>=4.5;
  const update=(patch)=>setDraft((value)=>({...value,config:{...value.config,...patch}}));
  const toggleSection=(section,enabled)=>update({sections:enabled?[...config.sections,section]:config.sections.filter((item)=>item!==section)});
  const mediaUrl=(id)=>media.find((asset)=>asset.id===id)?.ownerUrl||null;
  async function selectLayout(template){if(template===config.template||status!=="ready")return;const nextConfig={...config,template};setDraft((value)=>({...value,config:nextConfig}));if(wizardStep!=="look")return;try{setStatus("saving");setMessage("");const value=await saveDesignDraft({revision:draft.revision,config:nextConfig},session.csrf_token);setDraft(value);setSavedConfig(value.config);setMessage(`${layoutChoices.find((item)=>item.id===template)?.name} layout selected. You’ll add your brand next.`);setStatus("ready");}catch(error){setDraft((value)=>({...value,config:savedConfig}));setMessage(error.message);setStatus("error");}}
  async function save(){try{setStatus("saving");const value=await saveDesignDraft({revision:draft.revision,config},session.csrf_token);setDraft(value);setSavedConfig(value.config);setMessage("Design saved. Your live app is unchanged until you publish.");setStatus("ready");}catch(error){setMessage(error.message);setStatus("error");}}
  async function publish(){if(dirty){setMessage("Save your changes before publishing so the app you reviewed is the version that goes live.");return;}if(!globalThis.confirm?.("Publish this saved design to your customer app now?"))return;try{setStatus("publishing");const value=await publishDesign(session.csrf_token);await refreshVersions();setReadiness(await fetchReadiness());setMessage(`Version ${value.version} is now live. Your menu, prices, and orders were not changed.`);setStatus("ready");}catch(error){setMessage(error.message);setStatus("error");}}
  async function revert(item){if(!globalThis.confirm?.(`Restore version ${item.version}? Your menu and orders will not change.`))return;try{setStatus("publishing");const value=await revertDesign(item.id,session.csrf_token);const[nextDraft]=await Promise.all([fetchDesignDraft(),refreshVersions()]);setDraft(nextDraft);setSavedConfig(nextDraft.config);setMessage(`Version ${value.version} is live, restored from version ${item.version}.`);setStatus("ready");}catch(error){setMessage(error.message);setStatus("error");}}
  async function upload(event){const file=event.target.files?.[0];if(!file)return;try{setUploading(true);const asset=await uploadMedia(file,`${config.displayName} brand image`,session.csrf_token);setMedia((items)=>[asset,...items]);setMessage("Image uploaded to your private media library.");}catch(error){setMessage(error.message);}finally{setUploading(false);event.target.value="";}}
  async function removeMedia(asset){if(!globalThis.confirm?.(`Remove ${asset.altText||"this image"} from your library?`))return;try{await archiveMedia(asset.id,session.csrf_token);setMedia((items)=>items.filter((item)=>item.id!==asset.id));setMessage("Image removed from your library.");}catch(error){setMessage(error.message);}}
  return <section className={`design-studio ${wizardStep?`embedded-wizard-design wizard-design-${wizardStep}`:""}`}>
    {guided&&!wizardStep?<nav className="builder-progress" aria-label="Build your app progress">{builderStages.map((stage,index)=><Link className={index<2?"active":""} key={stage.label} to={stage.to}><span>{index+1}</span>{stage.label}</Link>)}</nav>:null}
    <header className="design-studio-header"><div><p className="eyebrow">{wizardStep==="look"?"Step 1":wizardStep==="brand"?"Step 2":guided?"Welcome to JDS":"Your storefront"}</p><h1>{wizardStep==="look"?"Choose your app layout.":wizardStep==="brand"?"Now make it yours.":guided?"Let’s build your ordering app.":"Design Studio"}</h1><p>{wizardStep==="look"?"Choose how your ordering app is organized. You’ll add your logo, colours and photos next.":wizardStep==="brand"?"Add your name, colours, images, and personality while your app updates beside you.":guided?"Start with a layout you love, then make every detail feel like your business.":"Change your app layout or branding anytime. Your menu, prices, and availability stay intact."}</p><p className={`draft-state ${dirty?"unsaved":"saved"}`}>{dirty?"Changes not saved yet · your live app is unchanged":"Your design is saved"}</p></div><div className="design-actions">{!wizardStep?<Link className="secondary-button" to="/admin/design/preview">Full preview</Link>:null}{wizardStep!=="look"?<button className="primary-button" disabled={status!=="ready"||!dirty||!contrastValid} onClick={save}>{status==="saving"?"Saving…":"Save my design"}</button>:null}{!guided?<button className="primary-button" disabled={status!=="ready"||dirty||!readiness?.checks} onClick={publish}>{status==="publishing"?"Publishing…":"Publish saved design"}</button>:null}</div></header>
    {message?<p className="owner-page-message" aria-live="polite">{message}</p>:null}<div className="mobile-studio-toggle" role="group" aria-label="Design workspace view"><button className={mobileView==="edit"?"active":""} onClick={()=>setMobileView("edit")} type="button">Edit</button><button className={mobileView==="preview"?"active":""} onClick={()=>setMobileView("preview")} type="button">Preview</button></div>
    <div className={`studio-workspace mobile-${mobileView}`}><aside className="studio-controls" aria-label="Design controls">
      <fieldset className="look-chooser layout-choice-grid"><legend>{guided?"Choose your app layout":"Choose an app layout"}</legend><p className="field-help">Each layout organizes navigation, categories, products and Quick Order differently. Your commerce data stays exactly the same.</p>{layoutChoices.map((item)=><label className={`layout-choice-card layout-choice-${item.id}`} key={item.id}><input disabled={status!=="ready"} type="radio" name="template" checked={config.template===item.id} onChange={()=>selectLayout(item.id)}/><span className="layout-card-miniature" aria-hidden="true"><i className="mini-header"/><i className="mini-hero"/><i className="mini-categories"/><i className="mini-products"/><i className="mini-nav"/></span><span className="layout-card-copy"><strong>{item.name}</strong><b>{item.personality}</b><small>{item.summary}</small></span><span className="layout-selected-mark">{config.template===item.id?"Selected":"Choose"}</span></label>)}</fieldset>
      {guided?<div className="builder-section-heading" id="brand"><span>2</span><div><h2>Make it yours</h2><p>Bring in your name, colours, images, and personality.</p></div></div>:null}<label>Business name<input value={config.displayName} maxLength="80" onChange={(event)=>update({displayName:event.target.value})}/></label><label>Tagline<input value={config.tagline} maxLength="140" onChange={(event)=>update({tagline:event.target.value})}/></label>
      <div className="color-controls">{Object.entries(config.colors).map(([key,value])=><label key={key}>{key}<input type="color" value={value} onChange={(event)=>update({colors:{...config.colors,[key]:event.target.value}})}/></label>)}</div>{!contrastValid?<p className="owner-page-message error" role="alert">Text needs at least 4.5:1 contrast against both the page background and card surface before this design can be saved.</p>:null}<label>Typography<select value={config.typography} onChange={(event)=>update({typography:event.target.value})}><option value="modern">Modern</option><option value="classic">Classic</option><option value="friendly">Friendly</option></select></label><label>Button style<select value={config.buttonStyle} onChange={(event)=>update({buttonStyle:event.target.value})}><option value="rounded">Rounded</option><option value="square">Square</option><option value="pill">Pill</option></select></label>
      <fieldset><legend>Media library</legend><p className="field-help">PNG, JPEG, or WebP up to 10 MB. Images assigned to this design or a live version are protected from removal.</p><label>Upload image<input type="file" accept="image/png,image/jpeg,image/webp" disabled={uploading} onChange={upload}/></label><label>Logo<select value={config.logoMediaId||""} onChange={(event)=>update({logoMediaId:event.target.value||null})}><option value="">No logo</option>{media.map((asset)=><option key={asset.id} value={asset.id}>{asset.altText||asset.storageKey||"Uploaded image"}</option>)}</select></label><label>Hero image<select value={config.hero?.mediaId||""} onChange={(event)=>update({hero:{mode:event.target.value?"image":"color",mediaId:event.target.value||null}})}><option value="">Use brand color</option>{media.map((asset)=><option key={asset.id} value={asset.id}>{asset.altText||asset.storageKey||"Uploaded image"}</option>)}</select></label>{media.length?<div className="media-library-grid">{media.map((asset)=>{const assigned=asset.id===config.logoMediaId||asset.id===config.hero?.mediaId;return <article key={asset.id}><img src={asset.ownerUrl} alt={asset.altText||"Uploaded brand image"}/><span>{asset.altText||"Brand image"}{assigned?" · Assigned":""}</span><button type="button" className="text-button" disabled={assigned} onClick={()=>removeMedia(asset)}>Remove</button></article>;})}</div>:<p className="preview-empty">Upload a logo or hero image to begin your reusable library.</p>}</fieldset>
      {config.template==="cozy"?<label className="checkbox-label"><input type="checkbox" checked={config.sections.includes("quickOrder")} onChange={(event)=>toggleSection("quickOrder",event.target.checked)}/>Show Quick Order on Home</label>:null}<label className="checkbox-label"><input type="checkbox" checked={config.announcement?.enabled||false} onChange={(event)=>update({announcement:{...(config.announcement||{text:""}),enabled:event.target.checked}})}/>Show announcement</label><label>Announcement<input value={config.announcement?.text||""} maxLength="180" onChange={(event)=>update({announcement:{...(config.announcement||{enabled:false}),text:event.target.value}})}/></label><fieldset><legend>Installed app appearance</legend><label>Short name<input value={config.pwa.shortName} maxLength="30" onChange={(event)=>update({pwa:{...config.pwa,shortName:event.target.value}})}/></label><label>Theme color<input type="color" value={config.pwa.themeColor} onChange={(event)=>update({pwa:{...config.pwa,themeColor:event.target.value}})}/></label><label>Launch background<input type="color" value={config.pwa.backgroundColor} onChange={(event)=>update({pwa:{...config.pwa,backgroundColor:event.target.value}})}/></label></fieldset>
      {guided?<aside className="builder-next"><span>Next</span><strong>{wizardStep==="look"?"Make this layout yours":"Tell us about your business"}</strong><p>{wizardStep==="look"?"Your layout choice saves automatically. Next, add your logo, colours and photos.":"Save your design, then add the details customers need to order with confidence."}</p>{wizardStep?<button className="primary-button" disabled={dirty||status!=="ready"} type="button" onClick={onContinue}>{wizardStep==="look"?"Continue to branding":"Continue to business details"}</button>:<Link className={`primary-button ${dirty?"disabled-link":""}`} aria-disabled={dirty} to={dirty?"#brand":"/admin/setup#business"}>Continue to business details</Link>}</aside>:<section className="design-history"><h2>Published versions</h2>{versions.length?<ul>{versions.map((item)=><li key={item.id}><span>Version {item.version}{item.isCurrent?" · Live":""}<small>{new Date(item.publishedAt).toLocaleString()}</small></span>{!item.isCurrent?<button className="secondary-button" type="button" disabled={status!=="ready"} onClick={()=>revert(item)}>Restore</button>:null}</li>)}</ul>:<p>Nothing has been published yet.</p>}</section>}
    </aside><div className="phone-preview-wrap"><p className="preview-badge">Your app preview</p><LayoutPhonePreview config={config} categories={categories} products={products} logoUrl={mediaUrl(config.logoMediaId)} heroUrl={mediaUrl(config.hero?.mediaId)}/><p className="preview-only-note">Preview only — customers can’t order yet.</p></div></div>
  </section>;
}
