import { useEffect, useState } from "react";
import { fetchPlatformOrganization, fetchPlatformOrganizations } from "../services/designStudioApi.js";
import { fetchPlatformActivationRequests, fetchPlatformDemoProspects, promoteDemoToLive } from "../services/demoFunnelApi.js";
import { useOwnerAuth } from "../auth/OwnerAuthContext.jsx";
import { hasPlatformCapability } from "../auth/ownerProductPermissions.js";

export default function PlatformAdminPage() {
  const {session}=useOwnerAuth();
  const canPromote=hasPlatformCapability(session,"platform.organizations.write");
  const [organizations,setOrganizations]=useState(null); const [error,setError]=useState("");const [detail,setDetail]=useState(null);const [loadingDetail,setLoadingDetail]=useState(false);
  const [prospects,setProspects]=useState([]); const [activations,setActivations]=useState([]);
  async function inspect(id){try{setLoadingDetail(true);setDetail(await fetchPlatformOrganization(id));}catch(reason){setError(reason.message);}finally{setLoadingDetail(false);}}
  async function promote(id){if(!globalThis.confirm?.("Promote this demo to live? Design, catalog, and media are preserved."))return;try{await promoteDemoToLive(id,{csrfToken:session.csrf_token});setProspects(await fetchPlatformDemoProspects());setActivations(await fetchPlatformActivationRequests());setOrganizations(await fetchPlatformOrganizations());}catch(reason){setError(reason.message);}}
  useEffect(()=>{Promise.all([fetchPlatformOrganizations(),fetchPlatformDemoProspects().catch(()=>[]),fetchPlatformActivationRequests().catch(()=>[])]).then(([orgs,demoProspects,requests])=>{setOrganizations(orgs);setProspects(demoProspects);setActivations(requests);}).catch((reason)=>setError(reason.message));},[]);
  return <section className="page-section platform-admin"><header><p className="eyebrow">JDS platform</p><h1>Organizations</h1><p>Operational status only. Customer details and credentials are not shown.</p></header>
    <section className="operations-panel"><h2>Demo prospects</h2><p className="build-store-disclosure">Funnel events and activation leads for controlled-pilot demos. Promote only after commercial agreement (~C$150/mo, JDS 0% of sales). Does not auto-bill.</p>{prospects.length===0?<p>No free demo prospects yet.</p>:<ul className="platform-prospect-list">{prospects.map((item)=><li key={item.id}><strong>{item.name}</strong><small>{item.slug} · created {item.createdAt}</small>{item.activation?<small>Activation: {item.activation.status} · {item.activation.email} · {item.activation.processorPreference}</small>:null}{item.recentActivity?.length?<small>Recent: {item.recentActivity.map((event)=>event.event).join(", ")}</small>:null}{canPromote?<button type="button" className="secondary-button" onClick={()=>promote(item.id)}>Promote to live</button>:<small>Promotion requires platform write access.</small>}</li>)}</ul>}</section>
    <section className="operations-panel"><h2>Activation requests</h2><p className="build-store-disclosure">Leads from Request activation. Review offline, then Promote to live when ready. Design/catalog/media are preserved.</p>{activations.length===0?<p>No activation requests.</p>:<ul>{activations.map((item)=><li key={item.id}><strong>{item.businessName}</strong><small>{item.contactName} · {item.email} · {item.city || "—"} · {item.processorPreference} · {item.status} · {item.createdAt}</small></li>)}</ul>}</section>
    {error?<div className="owner-page-message error"><strong>Platform access is restricted.</strong><p>{error}</p></div>:organizations===null?<p>Loading organization health…</p>:organizations.length===0?<p>No organizations have been provisioned.</p>:<div className="platform-table-wrap"><table><thead><tr><th>Business</th><th>Storefront</th><th>Readiness</th><th>Clover</th><th>Design</th><th>Subscription</th><th/></tr></thead><tbody>{organizations.map((item)=><tr key={item.id}><td><strong>{item.name}</strong><small>{item.ownerMemberships} owner membership{item.ownerMemberships===1?"":"s"}</small></td><td>{item.canonicalHost||"Not verified"}</td><td>{item.publicReady?"Public ready":item.onboarding.replaceAll("_"," ")}</td><td>{item.cloverHealth.join(", ").replaceAll("_"," ")}</td><td>{item.publishedVersionId?"Published":"Not published"}</td><td>{item.subscription.replaceAll("_"," ")}</td><td><button type="button" className="secondary-button" onClick={()=>inspect(item.id)}>Inspect</button></td></tr>)}</tbody></table></div>}
    {loadingDetail?<p>Loading operational detail…</p>:detail?<section className="operations-panel platform-detail"><h2>{detail.name}</h2><p>{detail.slug} · {detail.status}</p>{detail.warnings?.length?<aside className="platform-warnings"><h3>Operational warnings</h3><ul>{detail.warnings.map((warning)=><li key={warning}>{warning}</li>)}</ul></aside>:<p className="owner-page-message">No current operational warnings.</p>}<div className="platform-detail-grid"><section><h3>Readiness</h3><ul>{Object.entries(detail.readiness.checks).map(([key,value])=><li key={key}>{value?"Ready":"Needed"}: {key.replaceAll("_"," ")}</li>)}</ul></section><section><h3>Owner memberships</h3>{detail.owners?.length?<ul>{detail.owners.map((owner)=><li key={owner.membershipId}><strong>{owner.displayName}</strong><small>{owner.email} · {owner.status}</small></li>)}</ul>:<p>No owner assigned.</p>}</section><section><h3>Clover health</h3>{detail.clover?.length?<ul>{detail.clover.map((item)=><li key={`${item.environment}-${item.merchantReference}`}><strong>{item.connectionState.replaceAll("_"," ")}</strong><small>{item.environment} · merchant {item.merchantReference}</small></li>)}</ul>:<p>Not connected.</p>}</section><section><h3>Design and subscription</h3><p>{detail.design?.publishedVersionId?"Storefront design published":"No published design"}</p><p>{detail.subscription?`${detail.subscription.plan} · ${detail.subscription.state.replaceAll("_"," ")}`:"No subscription assigned"}</p></section></div><h3>Recent audit activity</h3>{detail.audit.length?<ol>{detail.audit.map((event,index)=><li key={`${event.occurredAt}-${index}`}><strong>{event.action}</strong> · {event.outcome}</li>)}</ol>:<p>No tenant operational events recorded.</p>}</section>:null}
  </section>;
}
